apiVersion: v1
data:
  DAGSTER_HOME: /opt/dagster/dagster_home
  DAGSTER_K8S_INSTANCE_CONFIG_MAP: dagster-instance
  DAGSTER_K8S_PG_PASSWORD_SECRET: dagster-postgresql-secret
  DAGSTER_K8S_PIPELINE_RUN_ENV_CONFIGMAP: dagster-pipeline-env
  DAGSTER_K8S_PIPELINE_RUN_IMAGE: docker.io/dagster/user-code-example:0.0.1-dev
  DAGSTER_K8S_PIPELINE_RUN_IMAGE_PULL_POLICY: Always
  DAGSTER_K8S_PIPELINE_RUN_NAMESPACE: dagster
kind: ConfigMap
metadata:
  labels:
    app: dagster
    chart: dagster-0.0.1-dev
    heritage: Helm
    release: dagster
  name: dagster-webserver-env
  namespace: dagster
