apiVersion: v1
data:
  DAGSTER_HOME: /opt/dagster/dagster_home
  DAGSTER_K8S_INSTANCE_CONFIG_MAP: dagster-dagster-user-deployments-instance
  DAGSTER_K8S_PG_PASSWORD_SECRET: dagster-postgresql-secret
  DAGSTER_K8S_PIPELINE_RUN_ENV_CONFIGMAP: dagster-dagster-user-deployments-pipeline-env
  DAGSTER_K8S_PIPELINE_RUN_NAMESPACE: dagster
kind: ConfigMap
metadata:
  labels:
    app: dagster-user-deployments
    chart: dagster-user-deployments-0.0.1-dev
    heritage: Helm
    release: dagster
  name: dagster-dagster-user-deployments-user-deployments-shared-env
  namespace: dagster
