apiVersion: v1
data:
  MB_DB_DBNAME: metabase
  MB_DB_HOST: database
  MB_DB_PASS: admin
  MB_DB_PORT: '5432'
  MB_DB_TYPE: postgres
  MB_DB_USER: admin
  MB_SITE_URL: https://metabase.k8s.tdad.jarv.us
kind: ConfigMap
metadata:
  name: metabase-config
  namespace: metabase
