apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: dagster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dagster-user-deployments
    app.kubernetes.io/version: dev
    helm.sh/chart: dagster-user-deployments-0.0.1-dev
  name: dagster-dagster-user-deployments-rolebinding
  namespace: dagster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dagster-dagster-user-deployments-role
subjects:
  - kind: ServiceAccount
    name: dagster-dagster-user-deployments-user-deployments
